# Generated by Django 3.0.4 on 2020-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Nombre Clave')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Red Social')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fcha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='FEcha de Edición')),
            ],
            options={
                'verbose_name': 'enlace',
                'verbose_name_plural': 'enlacescategorías',
                'ordering': ['name'],
            },
        ),
    ]
